config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  resources :users
  resources :questions do
    collection do
      get :solved
      get :unsolved
    end

    member do
      post :solve
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
end

app/models/questionz.rb
class Questionz < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required
  add_flash_types :success, :info, :warning, :danger
  

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :login_required, except: %i[index]
  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params.merge(user_id: current_user.id))
    if @question.save
      redirect_to questions_path(@question), success: '質問を投稿しました。'
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = current_user.questions.find(params[:id])

  end

  def update
    @question = current_user.questions.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_path, success: "質問「#{@question.title}」を更新しました。"
    end
  end

  def destroy
    @question = current_user.questions.find(params[:id])
    @question.destroy
    redirect_to questions_path, success: "質問「#{@question.title}」を削除しました。"
  end

  def solve
    @question = current_user.questions.find(params[:id])
    @question.update(solved_check: true)
    redirect_to questions_path(@question), success: '質問を解決済みにしました。'
  end
  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :login_required

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: session_params[:email])
    
    if @user &.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to users_path, notice: 'ログインしました。'
    else
      render :login
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :index]

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash_message' %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" >QuestionApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            
            <a class="nav-link" href="/questions">質問一覧</a>
            <% if current_user %>
              <%= link_to  "ログアウト", logout_path, method: :delete, class:"nav-link" %>
            <% else %>
              <a class="nav-link" href="/login">ログイン</a>
              <a class="nav-link" href="/users/new">新規ユーザー作成</a>
            <% end %>
            <% if current_user %>
              <%= "ログイン中のユーザーは#{current_user.name}さんです。" %>
              <a class="nav-link active" aria-current="page" href="/questions/new">質問投稿</a>
              <a class="nav-link active" aria-current="page" href="users">ユーザー一覧</a>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h2>質問編集画面</h2>

<%= form_with model: @question, local: true do |f| %>
  <div>
    <%= f.label :title, "質問タイトル" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body, "質問内容" %>
    <%= f.text_field :body %>
  </div>
  <%= f.submit "更新", disable_with: '更新中' %>
<% end %>

app/views/questions/index.html.erb
<h2>質問一覧 画面</h2>
<% @questions.each do |question| %>
  <li>
    <%= link_to question.title, question %>
    <% if question.solved_check %>
      <%= '解決済み' %>
    <% else %>
      <%= '未解決' %>
    <% end %>
  </li>
<% end %>

app/views/questions/new.html.erb
<h2>質問投稿画面</h2>
<%= form_with model: @question, local: true do |f| %>
  <div>
    <%= f.label :title, "質問タイトル" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body, "内容" %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit "Submit", disable_with: 'Submiting...' %>
<% end %>

app/views/questions/show.html.erb
<h2>質問詳細画面</h2>

<div>
  <h3>質問タイトル</h3>
  <%= @question.title %>
</div>
<div>
  <h3>質問内容</h3>
  <%= @question.body %>
</div>


<% if current_user.id == @question.user_id %>
  <div>
    <%= link_to  "編集", edit_question_path %>
    <%= link_to  "削除", question_path(@question), method: :delete, data: {confirm: "質問「#{@question.title}」を削除しますか？"}, class: 'btn-danger' %>
    <%= link_to  "解決済みにする",  solve_question_path, method: :update %>
  </div>
<% end %>

app/views/session/new.html.erb
<h2>ログイン画面</h2>

<%= form_with scope: :session	, local: true do |f| %>
  <div>
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password %>
  </div>
  <%= f.submit "ログイン", disable_with: 'Submiting...' %>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/users/_user.html.erb
<li><%= user.name %></li>

app/views/users/index.html.erb
<%= render @users %>

app/views/users/new.html.erb
<h1>ユーザー新規作成画面</h1>

<%= form_with model: @user, local: true do |f| %>
  <div>
    <%= f.label :name, "名前" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email, "メール" %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, "パスワード（確認）" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "登録", disable_with: 'Submiting...' %>
<% end %>
  